defaultPlatforms:
- linux/arm64
- linux/amd64

defaultBaseImage: us-west1-docker.pkg.dev/orchestration-build/base/static

builds:
- id: controlplane-mcp-server
  dir: .
  main: ./cmd/controlplane-mcp-server
  ldflags:
  - -s -w
  - -X github.com/upbound/controlplane-mcp-server/main.version={{.Env.VERSION}}